/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PoupancaRouteImport } from './routes/poupanca'
import { Route as GastosVariaveisRouteImport } from './routes/gastos-variaveis'
import { Route as DespesasFixasRouteImport } from './routes/despesas-fixas'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PoupancaRoute = PoupancaRouteImport.update({
  id: '/poupanca',
  path: '/poupanca',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosVariaveisRoute = GastosVariaveisRouteImport.update({
  id: '/gastos-variaveis',
  path: '/gastos-variaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasFixasRoute = DespesasFixasRouteImport.update({
  id: '/despesas-fixas',
  path: '/despesas-fixas',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/poupanca': typeof PoupancaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/poupanca': typeof PoupancaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/poupanca': typeof PoupancaRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoes'
    | '/despesas-fixas'
    | '/gastos-variaveis'
    | '/poupanca'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoes'
    | '/despesas-fixas'
    | '/gastos-variaveis'
    | '/poupanca'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/cartoes'
    | '/despesas-fixas'
    | '/gastos-variaveis'
    | '/poupanca'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoesRoute: typeof CartoesRoute
  DespesasFixasRoute: typeof DespesasFixasRoute
  GastosVariaveisRoute: typeof GastosVariaveisRoute
  PoupancaRoute: typeof PoupancaRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poupanca': {
      id: '/poupanca'
      path: '/poupanca'
      fullPath: '/poupanca'
      preLoaderRoute: typeof PoupancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-variaveis': {
      id: '/gastos-variaveis'
      path: '/gastos-variaveis'
      fullPath: '/gastos-variaveis'
      preLoaderRoute: typeof GastosVariaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas-fixas': {
      id: '/despesas-fixas'
      path: '/despesas-fixas'
      fullPath: '/despesas-fixas'
      preLoaderRoute: typeof DespesasFixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoesRoute: CartoesRoute,
  DespesasFixasRoute: DespesasFixasRoute,
  GastosVariaveisRoute: GastosVariaveisRoute,
  PoupancaRoute: PoupancaRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
