/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencimentosRouteImport } from './routes/vencimentos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PoupancaRouteImport } from './routes/poupanca'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GastosVariaveisRouteImport } from './routes/gastos-variaveis'
import { Route as DespesasFixasRouteImport } from './routes/despesas-fixas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecuperarSenhaEnviadoRouteImport } from './routes/recuperar-senha.enviado'

const VencimentosRoute = VencimentosRouteImport.update({
  id: '/vencimentos',
  path: '/vencimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PoupancaRoute = PoupancaRouteImport.update({
  id: '/poupanca',
  path: '/poupanca',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosVariaveisRoute = GastosVariaveisRouteImport.update({
  id: '/gastos-variaveis',
  path: '/gastos-variaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasFixasRoute = DespesasFixasRouteImport.update({
  id: '/despesas-fixas',
  path: '/despesas-fixas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaEnviadoRoute = RecuperarSenhaEnviadoRouteImport.update({
  id: '/enviado',
  path: '/enviado',
  getParentRoute: () => RecuperarSenhaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/poupanca': typeof PoupancaRoute
  '/recuperar-senha': typeof RecuperarSenhaRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vencimentos': typeof VencimentosRoute
  '/recuperar-senha/enviado': typeof RecuperarSenhaEnviadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/poupanca': typeof PoupancaRoute
  '/recuperar-senha': typeof RecuperarSenhaRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vencimentos': typeof VencimentosRoute
  '/recuperar-senha/enviado': typeof RecuperarSenhaEnviadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas-fixas': typeof DespesasFixasRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/poupanca': typeof PoupancaRoute
  '/recuperar-senha': typeof RecuperarSenhaRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/vencimentos': typeof VencimentosRoute
  '/recuperar-senha/enviado': typeof RecuperarSenhaEnviadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/cartoes'
    | '/configuracoes'
    | '/despesas-fixas'
    | '/gastos-variaveis'
    | '/login'
    | '/perfil'
    | '/poupanca'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/vencimentos'
    | '/recuperar-senha/enviado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/cartoes'
    | '/configuracoes'
    | '/despesas-fixas'
    | '/gastos-variaveis'
    | '/login'
    | '/perfil'
    | '/poupanca'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/vencimentos'
    | '/recuperar-senha/enviado'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/cadastro'
    | '/cartoes'
    | '/configuracoes'
    | '/despesas-fixas'
    | '/gastos-variaveis'
    | '/login'
    | '/perfil'
    | '/poupanca'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/vencimentos'
    | '/recuperar-senha/enviado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  CadastroRoute: typeof CadastroRoute
  CartoesRoute: typeof CartoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DespesasFixasRoute: typeof DespesasFixasRoute
  GastosVariaveisRoute: typeof GastosVariaveisRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PoupancaRoute: typeof PoupancaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VencimentosRoute: typeof VencimentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencimentos': {
      id: '/vencimentos'
      path: '/vencimentos'
      fullPath: '/vencimentos'
      preLoaderRoute: typeof VencimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poupanca': {
      id: '/poupanca'
      path: '/poupanca'
      fullPath: '/poupanca'
      preLoaderRoute: typeof PoupancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-variaveis': {
      id: '/gastos-variaveis'
      path: '/gastos-variaveis'
      fullPath: '/gastos-variaveis'
      preLoaderRoute: typeof GastosVariaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas-fixas': {
      id: '/despesas-fixas'
      path: '/despesas-fixas'
      fullPath: '/despesas-fixas'
      preLoaderRoute: typeof DespesasFixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha/enviado': {
      id: '/recuperar-senha/enviado'
      path: '/enviado'
      fullPath: '/recuperar-senha/enviado'
      preLoaderRoute: typeof RecuperarSenhaEnviadoRouteImport
      parentRoute: typeof RecuperarSenhaRoute
    }
  }
}

interface RecuperarSenhaRouteChildren {
  RecuperarSenhaEnviadoRoute: typeof RecuperarSenhaEnviadoRoute
}

const RecuperarSenhaRouteChildren: RecuperarSenhaRouteChildren = {
  RecuperarSenhaEnviadoRoute: RecuperarSenhaEnviadoRoute,
}

const RecuperarSenhaRouteWithChildren = RecuperarSenhaRoute._addFileChildren(
  RecuperarSenhaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  CadastroRoute: CadastroRoute,
  CartoesRoute: CartoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DespesasFixasRoute: DespesasFixasRoute,
  GastosVariaveisRoute: GastosVariaveisRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PoupancaRoute: PoupancaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VencimentosRoute: VencimentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
